import type { Metadata } from 'next';
import { Geist, Geist_Mono, Manrope, Mukta } from 'next/font/google';
import './globals.css';

const mukta = Mukta({
  subsets: ['latin'],
  weight: ['300', '400'],
});
const manrope = Manrope({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className} ${mukta.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
